name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Run unit tests
        run: npm run test:unit
      - name: Run e2e-tests
        run: npm run test:e2e:ci
